openapi: 3.0.0
info:
  title: banking-api-doc
  version: 1.0.0
servers:
  - url: http://{{local_base_url}}
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
paths:
  /api/register:
    post:
      tags:
        - default
      summary: 'Admin_Cachier: SignUp'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: Domou4 Brice4
                email: dbryzz.dev+4@gmail.com
                password: Password1
                role: ''
      security:
        - bearerAuth: []
      parameters:
        - name: X-Authorization
          in: header
          schema:
            type: string
          example: JTJ8fR5wkuppNrj6wTFSIU5TJUNS45L6ANDeeWhiWvpj8bxcpV5R3Gk8lHQml9Gl
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/login:
    post:
      tags:
        - default
      summary: SignIn
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: dbryzz.dev+2@gmail.com
                password: Password1
      parameters:
        - name: X-Authorization
          in: header
          schema:
            type: string
          example: JTJ8fR5wkuppNrj6wTFSIU5TJUNS45L6ANDeeWhiWvpj8bxcpV5R3Gk8lHQml9Gl
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/logout:
    post:
      tags:
        - default
      summary: Logout
      requestBody:
        content: {}
      security:
        - bearerAuth: []
      parameters:
        - name: X-Authorization
          in: header
          schema:
            type: string
          example: JTJ8fR5wkuppNrj6wTFSIU5TJUNS45L6ANDeeWhiWvpj8bxcpV5R3Gk8lHQml9Gl
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/refresh:
    post:
      tags:
        - default
      summary: RefreshToken
      requestBody:
        content: {}
      security:
        - bearerAuth: []
      parameters:
        - name: X-Authorization
          in: header
          schema:
            type: string
          example: JTJ8fR5wkuppNrj6wTFSIU5TJUNS45L6ANDeeWhiWvpj8bxcpV5R3Gk8lHQml9Gl
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/account/create:
    post:
      tags:
        - default
      summary: CreateAccount
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                type: savings
                initialDeposit: 38000
      security:
        - bearerAuth: []
      parameters:
        - name: X-Authorization
          in: header
          schema:
            type: string
          example: JTJ8fR5wkuppNrj6wTFSIU5TJUNS45L6ANDeeWhiWvpj8bxcpV5R3Gk8lHQml9Gl
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/account/status-change:
    patch:
      tags:
        - default
      summary: 'Admin: ChangeAccountStatus'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                accountId: 7
                status: blocked
      security:
        - bearerAuth: []
      parameters:
        - name: X-Authorization
          in: header
          schema:
            type: string
          example: JTJ8fR5wkuppNrj6wTFSIU5TJUNS45L6ANDeeWhiWvpj8bxcpV5R3Gk8lHQml9Gl
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/account/balance/get:
    get:
      tags:
        - default
      summary: GetMyBalance
      security:
        - bearerAuth: []
      parameters:
        - name: X-Authorization
          in: header
          schema:
            type: string
          example: JTJ8fR5wkuppNrj6wTFSIU5TJUNS45L6ANDeeWhiWvpj8bxcpV5R3Gk8lHQml9Gl
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/account/{accountId}/balance/get:
    get:
      tags:
        - default
      summary: 'Admin_Cachier: GetAccountBalance'
      security:
        - bearerAuth: []
      parameters:
        - name: X-Authorization
          in: header
          schema:
            type: string
          example: JTJ8fR5wkuppNrj6wTFSIU5TJUNS45L6ANDeeWhiWvpj8bxcpV5R3Gk8lHQml9Gl
        - name: accountId
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/transaction/initiate:
    post:
      tags:
        - default
      summary: InitiateTransaction
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                transactionType: withdrawal
                accountId: 2
                amount: 5000
                toAccountNumber: ''
                transferMotive: ''
      security:
        - bearerAuth: []
      parameters:
        - name: X-Authorization
          in: header
          schema:
            type: string
          example: JTJ8fR5wkuppNrj6wTFSIU5TJUNS45L6ANDeeWhiWvpj8bxcpV5R3Gk8lHQml9Gl
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/account/transfers:
    get:
      tags:
        - default
      summary: GetMyTransfers
      security:
        - bearerAuth: []
      parameters:
        - name: X-Authorization
          in: header
          schema:
            type: string
          example: JTJ8fR5wkuppNrj6wTFSIU5TJUNS45L6ANDeeWhiWvpj8bxcpV5R3Gk8lHQml9Gl
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/account/{accountId}/transfers:
    get:
      tags:
        - default
      summary: 'Admin_Cachier: GetAccountTransfers'
      security:
        - bearerAuth: []
      parameters:
        - name: X-Authorization
          in: header
          schema:
            type: string
          example: JTJ8fR5wkuppNrj6wTFSIU5TJUNS45L6ANDeeWhiWvpj8bxcpV5R3Gk8lHQml9Gl
        - name: accountId
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
